apiVersion: apps/v1
kind: Deployment
metadata:
  name: MyProduct
  labels:
    app: MyProduct
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MyProduct
  template:
    metadata:
      labels:
        app: MyProduct
    spec:
      containers:
        - name: MyProduct
          image: username/MyProduct:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5